default: &default
  sender_email: 'sender_email'
  address: 'smtp.gmail.com'
  port: '587'
  domain: 'gmail.com'
  user_name: 'sender_email'
  password: 'password'
  authentication: 'plain'

development:
  <<: *default

production:
  <<: *default
